dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy3.5"
os:
  - linux
before_script:
  - python -m pip install pip --upgrade
  - python -m pip list
  - export PYTHONHASHSEED=${PYTHONHASHSEED:-${RANDOM}}
  - echo "export PYTHONHASHSEED=${PYTHONHASHSEED}"
  - pip install .[contrib]
  - pip install codecov
  - export COVERAGE_PROCESS_START=$(pwd)/.coveragerc
  - export PYTEST_ADDOPTS=-v
script:
  - python -m flake8 -v src/ cobald_tests/
  - python -m black  --target-version py36 --check src/ cobald_tests/
  - coverage run setup.py test
after_success:
  - coverage report && codecov
